### ISSUE TITLE
快改

### ISSUE THREAD

**Issue by somewyveo** [SuperSkidder/TomorrowClient#2]
speed scaffold invmove gui改改 写个reach 杀戮开block走不动开noslow也没用 加个timer 加个xray

**Comment by SuperSkidder** [comment]
speed已修复
scaffold已修复
invmove暂无能力
gui已修改，请描述具体建议
reach将在R1.7添加
杀戮开block走不动是正常现象，请打开noslow，新版本noslow已修复
timer已添加
xray已添加
tips:提交时请分开提交
